# Generated by Django 5.2.7 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelanguage',
            name='language_code',
            field=models.CharField(max_length=200),
        ),
    ]
