# Generated by Django 5.2.7 on 2026-02-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0002_alter_employeelanguage_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='employee_documents/'),
        ),
    ]
