# Generated by Django 5.2.7 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIME_TABLE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureplan',
            name='document_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
