# Generated by Django 5.2.7 on 2026-02-10 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acadix', '0004_studentfeereceiptheader_receipt_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeachingStaffMaster',
            fields=[
                ('nts_id', models.AutoField(db_column='nts_id', primary_key=True, serialize=False)),
                ('staff_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('profile_pic', models.FileField(blank=True, max_length=255, null=True, upload_to='non_teaching_staff_pics/')),
                ('profile_photo_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits', regex='^\\d{6}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.blood')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.country')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.gender')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.state')),
            ],
            options={
                'db_table': 'NonTeachingStaffMaster',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'branch', 'status'], name='NonTeaching_organiz_016601_idx'), models.Index(fields=['staff_code'], name='NonTeaching_staff_c_478d65_idx')],
            },
        ),
    ]
