# Generated by Django 5.2.7 on 2026-02-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0004_studentfeereceiptheader_receipt_amount_and_more'),
        ('NON_TEACHING_STAFF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonteachingstaffmaster',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nonteachingstaffmaster',
            name='marital_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nonteachingstaffmaster',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.nationality'),
        ),
        migrations.AddField(
            model_name='nonteachingstaffmaster',
            name='official_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonteachingstaffmaster',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonteachingstaffmaster',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.religion'),
        ),
    ]
