TRUNCATE TABLE public.stg_student_import;
INSERT INTO public.stg_student_import (
    session_batch, course, department, academic_year, semester, section, onmrc_registration_no, first_name, middle_name, last_name, gender, date_of_birth, religion, category, nationality, blood_group, mother_tongue, admission_type, student_phone_number, student_email_id, student_aadhar_number, father_name, father_profession, father_phone_number, father_email_id, father_aadhar_number, mother_name, mother_profession, mother_phone_number, mother_email_id, mother_aadhar_number, address_in_details
) VALUES
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316086', 'MIHIR KUMAR GIRI', NULL, NULL, 'Male', NULL, NULL, 'GENERAL', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316100', 'SUVENDU BAL', NULL, NULL, 'Male', NULL, NULL, 'GENERAL', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316076', 'BIBHU PRASAD JENA', NULL, NULL, 'Male', NULL, NULL, 'SC', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316089', 'PURNENDU MALLICK', NULL, NULL, 'Male', NULL, NULL, 'SC', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316098', 'SUJIT DALEI', NULL, NULL, 'Male', NULL, NULL, 'SC', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316078', 'CHANDAN MALLICK', NULL, NULL, 'Male', NULL, NULL, 'SC', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '7852923119/ 9390799986', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316094', 'SHUBHAM KUMAR BARIK', NULL, NULL, 'Male', NULL, NULL, 'GENERAL', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, 'UGRASEN BARIK', NULL, '8249075584/ 8260588629', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('2024-2028', 'BTECH', 'CSE(DS)', '1st year', 'Semester 2', 'Section A', '2401316083', 'KHUSI MONDAL', NULL, NULL, 'Female', NULL, NULL, 'GENERAL', 'Indian', NULL, NULL, NULL, NULL, NULL, NULL, 'RAMKRISHNA MONDAL', NULL, '9438561409/ 8480249917', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
