# Generated by Django 5.2.7 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTORY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
