# Generated by Django 5.2.7 on 2026-03-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTORY', '0002_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_location',
                field=models.CharField(blank=True, choices=[('Medical', 'Medical'), ('Hostel', 'Hostel'), ('Bhubaneswar Engineering College', 'Bhubaneswar Engineering College')], max_length=50, null=True),
        ),
    ]
