# Generated by Django 5.2.7 on 2026-01-24 14:52

import Acadix.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='section',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentassignment',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='studentfeereceiptheader',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='studentfeereceiptheader',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='studentfeereceiptheader',
            name='receipt_amount',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='bank_account_id',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='lecture',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_sms_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='temp_hostel_choice_semester',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentfeereceiptheader',
            name='payment_detail',
            field=models.JSONField(default=dict, validators=[Acadix.models.validate_payment_details]),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.bank'),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.bankaccountdetail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.house'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='admission_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.blood'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.category'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_join',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='father_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_aadhaar_no', message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.gender'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='house',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.house'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='mother_aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_aadhaar_no', message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='mother_tongue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.mothertongue'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.nationality'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='primary_guardian',
            field=models.CharField(blank=True, default='FATHER', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.religion'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('batch', 'course_code')},
        ),
        migrations.CreateModel(
            name='LecturePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_period_name', models.CharField(max_length=20)),
                ('lecture_period_description', models.CharField(blank=True, max_length=50, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('day_attendance', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.lectureperiod'),
        ),
        migrations.AddField(
            model_name='studentassignment',
            name='lecture_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.lectureperiod'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lecture_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.lectureperiod'),
        ),
        migrations.CreateModel(
            name='StudentBonafideCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=5000, null=True)),
                ('certificate_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('created_by', models.PositiveIntegerField(default=1)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCharacterCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('certificate_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('student_behaviour', models.CharField(blank=True, max_length=5000, null=True)),
                ('created_by', models.PositiveIntegerField(default=1)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=5000, null=True)),
                ('certificate_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('created_by', models.PositiveIntegerField(default=1)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTransferCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_number', models.CharField(max_length=1000)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('reason_of_leaving', models.CharField(blank=True, max_length=500, null=True)),
                ('student_behaviour', models.CharField(blank=True, max_length=500, null=True)),
                ('certificate_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=100)),
                ('readmission_eligibility', models.CharField(choices=[('Eligible', 'Eligible'), ('Ineligible', 'Ineligible')], default='Eligible', max_length=100)),
                ('created_by', models.PositiveIntegerField(default=1)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.studentregistration')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentCertificate',
        ),
    ]
