# Generated by Django 5.2.7 on 2026-01-27 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0002_remove_attendance_lecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.lecture'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.academicyear'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.batch'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.department'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.section'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.semester'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lecture_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acadix.lectureperiod'),
        ),
        migrations.AlterField(
            model_name='exceptiontrack',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exceptiontrack',
            name='request',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studentassignment',
            name='lecture_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acadix.lectureperiod'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lecture_period',
            field=models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, to='Acadix.lectureperiod'),
        ),
    ]
