# Generated by Django 5.2.7 on 2026-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0003_attendance_lecture_lecture_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeereceiptheader',
            name='receipt_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='accessible_modules',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
