# Generated by Django 5.2.7 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0004_studentfeereceiptheader_receipt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='role_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
