# Generated by Django 5.2.7 on 2026-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0005_userlogin_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='reference_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
