# Generated by Django 5.2.7 on 2026-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0006_alter_userlogin_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
