# Generated by Django 5.2.7 on 2026-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0007_semester_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorisedpickup',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='authorisedpickup',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
