# Generated by Django 5.2.7 on 2026-02-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0008_authorisedpickup_address_authorisedpickup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='referred_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
