# Generated by Django 5.2.7 on 2026-02-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0009_studentregistration_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='nuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
