# Generated by Django 5.2.7 on 2026-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0010_employeemaster_nuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeereceiptheader',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
