# Generated by Django 5.2.7 on 2026-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0011_studentfeereceiptheader_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeereceiptheader',
            name='cancelled_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfeereceiptheader',
            name='cancelled_by_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
