# Generated by Django 5.2.7 on 2026-04-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acadix', '0016_alter_department_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructuremaster',
            name='fee_structure_code',
            field=models.CharField(max_length=255),
        ),
    ]
