# Generated by Django 5.2.7 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REPORT_CARD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamresult',
            name='as_on_date',
            field=models.DateField(blank=True, help_text='Date when health status was recorded (YYYY-MM-DD format)', null=True),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='height',
            field=models.CharField(blank=True, help_text="Height (can be string or number, e.g., '150', '150cm', or 150)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentexamresult',
            name='weight',
            field=models.CharField(blank=True, help_text="Weight (can be string or number, e.g., '45', '45kg', or 45)", max_length=50, null=True),
        ),
    ]
