# Generated by Django 5.2.7 on 2026-02-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MENTOR', '0002_alter_table_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorstudentcommunication',
            name='communication_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
